### ocean eddy kinetic energy

In [1]:
import jdcal, datetime
import numpy as np
import xarray as xr

In [2]:
path = '/home/cz2397/data/ssh-eddies/tracks_AVISO_DT2014_daily_web.nc'
ds = xr.open_dataset(path, decode_cf=False)

In [3]:
df = ds.to_dataframe()

In [4]:
df.head()

track  n       j1  cyc         lon        lat          A           L  \
Nobs                                                                         
0         1  1  2448989    1  397.040985 -21.719400  31.473101  146.738998   
1         1  2  2448990    1  397.015991 -21.760300  30.215599  138.673996   
2         1  3  2448991    1  397.003998 -21.797701  28.817200  137.839996   
3         1  4  2448992    1  396.971008 -21.852100  28.791300  136.145996   
4         1  5  2448993    1  396.945007 -21.871201  27.741199  136.119995   

              U  
Nobs             
0     79.148399  
1     79.141296  
2     78.532097  
3     77.241402  
4     77.705101

** date **

In [5]:
ds.j1

<xarray.DataArray 'j1' (Nobs: 22510604)>
array([2448989, 2448990, 2448991, ..., 2457133, 2457134, 2457135], dtype=int32)
Unindexed dimensions:
    Nobs
Attributes:
    units: days
    min: 2448989
    max: 2457136
    long_name: Julian date
    description: date of this observation
    reference: 2448623
    reference_description: Julian date at Jan 1, 1992

In [6]:
def jd_to_dt(jd, ref=0):
    y, m, d, f = jdcal.jd2gcal(jd, ref)
    h = int(f*24)
    return datetime.datetime(y, m, d, h)
jd_to_dt_v = np.vectorize(jd_to_dt)

In [7]:
ds_j1_dt = jd_to_dt_v(ds.j1.values)
ds.j1.values = ds_j1_dt

In [8]:
df = ds.to_dataframe()

In [9]:
df.head()

track  n                  j1  cyc         lon        lat          A  \
Nobs                                                                        
0         1  1 1993-01-01 12:00:00    1  397.040985 -21.719400  31.473101   
1         1  2 1993-01-02 12:00:00    1  397.015991 -21.760300  30.215599   
2         1  3 1993-01-03 12:00:00    1  397.003998 -21.797701  28.817200   
3         1  4 1993-01-04 12:00:00    1  396.971008 -21.852100  28.791300   
4         1  5 1993-01-05 12:00:00    1  396.945007 -21.871201  27.741199   

               L          U  
Nobs                         
0     146.738998  79.148399  
1     138.673996  79.141296  
2     137.839996  78.532097  
3     136.145996  77.241402  
4     136.119995  77.705101

** longitude **

In [10]:
ds.lon

<xarray.DataArray 'lon' (Nobs: 22510604)>
array([ 397.040985,  397.015991,  397.003998, ...,  333.492004,  332.901001,
        332.738007], dtype=float32)
Unindexed dimensions:
    Nobs
Attributes:
    units: degrees east
    min: 262.949
    max: 649.179
    long_name: longitude
    description: longitude of this observation
    note: To avoid jumps of ~360 deg in eddy tracks when the trajectory wraps around a longitude branch point that might lie in a region of interest, the longitude domain is set to 260E-650E. With this range, the only eddies with trajectories that might be affected will be those passing through the Drake Passage.

In [11]:
def range_180(longitude):
    if 260 < longitude <= 540:
        longitude = longitude - 360
    elif 540 < longitude <= 650:
        longitude = longitude - 720
    return longitude
range_180_v = np.vectorize(range_180)

In [12]:
ds_lon_180 = range_180_v(ds.lon.values)
ds.lon.values = ds_lon_180

In [13]:
df = ds.to_dataframe()

In [14]:
df.head()

track  n                  j1  cyc        lon        lat          A  \
Nobs                                                                       
0         1  1 1993-01-01 12:00:00    1  37.040985 -21.719400  31.473101   
1         1  2 1993-01-02 12:00:00    1  37.015991 -21.760300  30.215599   
2         1  3 1993-01-03 12:00:00    1  37.003998 -21.797701  28.817200   
3         1  4 1993-01-04 12:00:00    1  36.971008 -21.852100  28.791300   
4         1  5 1993-01-05 12:00:00    1  36.945007 -21.871201  27.741199   

               L          U  
Nobs                         
0     146.738998  79.148399  
1     138.673996  79.141296  
2     137.839996  78.532097  
3     136.145996  77.241402  
4     136.119995  77.705101

** latitude **

In [15]:
ds.lat

<xarray.DataArray 'lat' (Nobs: 22510604)>
array([-21.7194  , -21.7603  , -21.797701, ..., -17.0242  , -16.863001, -16.7901  ], dtype=float32)
Unindexed dimensions:
    Nobs
Attributes:
    units: degrees north
    min: -77.3894
    max: 79.2183
    long_name: latitude
    description: latitude of this observation (negative for southern hemisphere)

** amplitude **

In [16]:
ds.A

<xarray.DataArray 'A' (Nobs: 22510604)>
array([ 31.473101,  30.215599,  28.8172  , ...,   1.36601 ,   1.31433 ,
         1.07771 ], dtype=float32)
Unindexed dimensions:
    Nobs
Attributes:
    units: cm
    min: 1.0
    max: 48.4769
    long_name: amplitude
    description: magnitude of the height difference between the extremum of SSH within the eddy and the SSH around the contour defining the eddy perimeter

In [17]:
ds_A_meters = ds.A.values*0.01
ds.A.values = ds_A_meters

In [18]:
df = ds.to_dataframe()

In [19]:
df.head()

track  n                  j1  cyc        lon        lat         A  \
Nobs                                                                      
0         1  1 1993-01-01 12:00:00    1  37.040985 -21.719400  0.314731   
1         1  2 1993-01-02 12:00:00    1  37.015991 -21.760300  0.302156   
2         1  3 1993-01-03 12:00:00    1  37.003998 -21.797701  0.288172   
3         1  4 1993-01-04 12:00:00    1  36.971008 -21.852100  0.287913   
4         1  5 1993-01-05 12:00:00    1  36.945007 -21.871201  0.277412   

               L          U  
Nobs                         
0     146.738998  79.148399  
1     138.673996  79.141296  
2     137.839996  78.532097  
3     136.145996  77.241402  
4     136.119995  77.705101

** radius **

In [20]:
ds.L

<xarray.DataArray 'L' (Nobs: 22510604)>
array([ 146.738998,  138.673996,  137.839996, ...,  106.345001,   82.703598,
         76.799698], dtype=float32)
Unindexed dimensions:
    Nobs
Attributes:
    units: km
    min: 8.93032
    max: 444.603
    long_name: radius scale
    description: radius of a circle whose area is equal to that enclosed by the contour of maximum circum-average speed

In [21]:
ds_L_meters = ds.L.values*1000
ds.L.values = ds_L_meters

In [22]:
df = ds.to_dataframe()

In [23]:
df.head()

track  n                  j1  cyc        lon        lat         A  \
Nobs                                                                      
0         1  1 1993-01-01 12:00:00    1  37.040985 -21.719400  0.314731   
1         1  2 1993-01-02 12:00:00    1  37.015991 -21.760300  0.302156   
2         1  3 1993-01-03 12:00:00    1  37.003998 -21.797701  0.288172   
3         1  4 1993-01-04 12:00:00    1  36.971008 -21.852100  0.287913   
4         1  5 1993-01-05 12:00:00    1  36.945007 -21.871201  0.277412   

           L          U  
Nobs                     
0     146739  79.148399  
1     138674  79.141296  
2     137840  78.532097  
3     136146  77.241402  
4     136120  77.705101

** speed **

In [24]:
ds.U

<xarray.DataArray 'U' (Nobs: 22510604)>
array([ 79.148399,  79.141296,  78.532097, ...,   6.05052 ,   5.84693 ,
         5.63855 ], dtype=float32)
Unindexed dimensions:
    Nobs
Attributes:
    units: cm/sec
    min: 1.08407
    max: 671.569
    long_name: maximum circum-averaged speed
    description: average speed of the contour defining the radius scale L

In [25]:
ds_U_m_s = ds.U.values*0.01
ds.U.values = ds_U_m_s

In [26]:
df = ds.to_dataframe()

In [27]:
df.head()

track  n                  j1  cyc        lon        lat         A  \
Nobs                                                                      
0         1  1 1993-01-01 12:00:00    1  37.040985 -21.719400  0.314731   
1         1  2 1993-01-02 12:00:00    1  37.015991 -21.760300  0.302156   
2         1  3 1993-01-03 12:00:00    1  37.003998 -21.797701  0.288172   
3         1  4 1993-01-04 12:00:00    1  36.971008 -21.852100  0.287913   
4         1  5 1993-01-05 12:00:00    1  36.945007 -21.871201  0.277412   

           L         U  
Nobs                    
0     146739  0.791484  
1     138674  0.791413  
2     137840  0.785321  
3     136146  0.772414  
4     136120  0.777051